### ISSUE TITLE
WildChests Lag

### ISSUE THREAD

**Issue by DJDanTheMan** [BG-Software-LLC/WildChests#8] opened 2021-01-28 16:36 UTC
Hi,

I'm using the jar you sent me before of wild chests, and somehow I'm still getting lag. I wondering if it when I update wild stacker to 3.5.1 cause it didn't start to occur before then. here is the sampler you wanted from spark https://spark.lucko.me/#J07o06rDYM.

I hope you can help fix my lag

**Comment by OmerBenGera** [comment] 2021-01-28 21:36
Take a spark profiler using /spark sampler when the lag occurs. When it's done, run /spark sampler --stop and send me the link.
The link above is a heap dump and it's useless

**Comment by DJDanTheMan** [comment] 2021-01-29 01:16
sorry here is the sampler https://spark.lucko.me/#9hVyCh2Rhp

**Comment by OmerBenGera** [comment] 2021-01-29 10:48
You're using an obfuscated verison of WildChests, which are no longer supported.
Please use latest dev build and take a new spark sampler using it

**Comment by OmerBenGera** [comment] 2021-01-29 10:51
But, from what I can see, it's a lag caused by Essentials - it should be better in latest versions tho, so it might be a good thing to check them out and give them a go

**Comment by DJDanTheMan** [comment] 2021-02-28 17:05
If it helps you resolve this issue I'm using essentials 2.0.1 b268 and I tried with the latest dev build of wild chests, and I'm still getting lag. I will post a new spark sampler soon.

**Comment by OmerBenGera** [comment] 2021-02-28 17:30
As I said, the lag comes from Essentials economy provider, which struggles with handling more than 5 requests at a time due to how badly it's coded.

**Comment by OmerBenGera** [comment] 2021-03-17 13:50
An issue was opened by another customer having issues on their github, however they closed it.
I commented on it, hopefully it will be fixed soon.
https://github.com/EssentialsX/Essentials/issues/4060

**Comment by OmerBenGera** [comment] 2021-03-29 19:41
I am closing this as it has nothign to do with the plugin
I can't make a PR as I don't have time, hopefully they will fix it soon

**Closed by OmerBenGera** 2021-03-29 19:41 UTC
Labels: Bug Report

**Comment by DJDanTheMan** [comment] 2021-10-03 22:14
My issue is still occurring, what else can you recommend?

**Comment by OmerBenGera** [comment] 2021-10-04 05:23
> My issue is still occurring, what else can you recommend?

Contact Essentials regarding this, and look at the issue I mentioned above.
